import {
  assertSingleSegment,
  classifyStepEffect,
  deriveNetworkEffect,
  redactUrl,
  redactValue,
  roundUpEffect,
  SchemaExhaustedError,
  type EffectTag,
  type LlmBackend,
  type Recording,
  type Step,
} from "@skillwright/shared";
import { toSlug } from "../slug";
import { stepLabel } from "../step-label";
import { distill, type DistillOptions, type SkillDirectory } from "../distill";
import { scrubText, sanitizeSkillDescription } from "./sanitize";
import { inferEffects, inferIntent, inferParams, narrate, type ParamDef, type StepNarrative } from "./passes";

interface RenderedStep {
  index: number;
  type: string;
  effect: EffectTag;
  selectors: string[][];
  value?: string;
  url?: string;
  narrative: StepNarrative;
}

/** Rewrite a captured value: promote a known demo value to its placeholder,
 * otherwise redact anything secret-shaped. */
function rewriteValue(raw: string, params: ParamDef[]): string {
  const param = params.find((p) => p.demoValue === raw);
  if (param) return `{${param.name}}`;
  return redactValue(raw);
}

/** Effect = the LLM tag rounded UP by the non-LLM heuristic floor (§6.1). The
 * heuristic can only raise severity, never lower it — the safety-net for a
 * model that under-tags a destructive control. */
function combineEffect(step: Step, llmEffect: EffectTag): EffectTag {
  const heuristic = classifyStepEffect({ action: step.type, label: stepLabel(step) });
  // Network truth (the HTTP method the step fired) is a non-LLM floor.
  const network = deriveNetworkEffect(step.requests ?? []);
  return roundUpEffect(network ? [llmEffect, heuristic, network] : [llmEffect, heuristic]);
}

function frontmatter(slug: string, description: string, params: ParamDef[]): string {
  const inputs = params.map((p) => ({ name: p.name, type: p.type, required: p.required }));
  // Emit description as a quoted YAML scalar over a whitespace-collapsed, length-
  // capped value: a raw newline or leading special char would break the
  // frontmatter and no agent could load the skill.
  const safeDescription = JSON.stringify(sanitizeSkillDescription(description));
  return [
    "---",
    `name: ${slug}`,
    `description: ${safeDescription}`,
    "compatibility: Requires Node 20+, a Chrome CDP endpoint (skillwright relay), and an authenticated session in that browser.",
    "metadata:",
    "  author: skillwright",
    '  version: "1.0"',
    `  skillwright-inputs: '${JSON.stringify(inputs)}'`,
    "---",
  ].join("\n");
}

function renderSkillMd(
  slug: string,
  title: string,
  description: string,
  params: ParamDef[],
  rendered: RenderedStep[],
): string {
  const lines = [
    "",
    `# ${title}`,
    "",
    description,
    "",
    `Replay with \`skillwright run ${slug}\`. Full step detail, selector stacks, and screenshots`,
    "are in `references/walkthrough.md`.",
    "",
  ];
  if (params.length > 0) {
    lines.push("## Inputs", "");
    for (const p of params) {
      lines.push(`- \`{${p.name}}\` (${p.type}${p.required ? ", required" : ""})${p.description ? ` — ${p.description}` : ""}`);
    }
    lines.push("");
  }
  lines.push("## Steps", "");
  rendered.forEach((r, i) => {
    const tag = r.narrative.agentStep ? "agent" : r.effect;
    lines.push(`${i + 1}. [${tag}] ${r.narrative.description}`);
  });
  lines.push("");
  return frontmatter(slug, description, params) + "\n" + lines.join("\n");
}

function renderReplayScript(slug: string, rendered: RenderedStep[]): string {
  // Judgment steps are prose in SKILL.md and are NEVER frozen into code (§6.1).
  const steps = rendered
    .filter((r) => !r.narrative.agentStep)
    .map((r) => {
      const step: Record<string, unknown> = { type: r.type, effect: r.effect, selectors: r.selectors };
      if (r.value !== undefined) step.value = r.value;
      if (r.url !== undefined) step.url = r.url;
      return step;
    });
  return [
    `// Auto-generated by skillwright distill for "${slug}". Do not hand-edit;`,
    `// re-run distill or let a heal write back through the CLI.`,
    `// Convenience runner — the canonical path is \`skillwright run ${slug}\`.`,
    `import { chromium } from "playwright";`,
    `import { runSkill, PlaywrightStepDriver } from "skillwright";`,
    "",
    `export const steps = ${JSON.stringify(steps, null, 2)} as const;`,
    "",
    `export async function run(`,
    `  cdpUrl = process.env.CHROME_CDP_URL,`,
    `  { confirmDestructive = false } = {},`,
    `) {`,
    `  if (!cdpUrl) throw new Error("CHROME_CDP_URL is not set — start 'skillwright relay'.");`,
    `  const browser = await chromium.connectOverCDP(cdpUrl);`,
    `  try {`,
    `    const context = browser.contexts()[0] ?? (await browser.newContext());`,
    `    const page = context.pages()[0] ?? (await context.newPage());`,
    `    const driver = new PlaywrightStepDriver(page);`,
    `    const result = await runSkill(steps as unknown as Parameters<typeof runSkill>[0], driver, {`,
    `      confirmDestructive,`,
    `    });`,
    `    if (result.status !== "ok") {`,
    `      throw new Error(\`replay \${result.status}: \${JSON.stringify(("report" in result && result.report) || {})}\`);`,
    `    }`,
    `    return result;`,
    `  } finally {`,
    `    await browser.close();`,
    `  }`,
    `}`,
    "",
  ].join("\n");
}

function renderWalkthrough(title: string, rendered: RenderedStep[]): string {
  const lines = [`# ${title} — walkthrough`, ""];
  for (const r of rendered) {
    lines.push(`## Step ${r.index + 1}: ${r.narrative.description}`);
    lines.push(`- effect: ${r.narrative.agentStep ? "agent (judgment step, not scripted)" : r.effect}`);
    if (r.selectors.length > 0) {
      lines.push("- selectors (most stable first):");
      for (const stack of r.selectors) lines.push(`  - ${stack.join(" → ")}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderChangelog(slug: string, recordedAt: string): string {
  return [`# Changelog — ${slug}`, "", "## 1.0 — distilled", `- Created from recording captured ${recordedAt} (skillwright distill, semantic mode).`, ""].join("\n");
}

/** Redacted, effect-tagged copy of the recording — immutable evidence, never
 * raw-with-secrets (§7). */
function redactedRecording(recording: Recording, params: ParamDef[], effects: EffectTag[]): Recording {
  return {
    ...recording,
    steps: recording.steps.map((step, i) => {
      const out: Step = { ...step, effect: effects[i]! };
      if (typeof step.value === "string") out.value = rewriteValue(step.value, params);
      if (typeof step.url === "string") out.url = redactUrl(step.url);
      return out;
    }),
  };
}

/**
 * Semantic (M2) distiller: run the four LLM passes, fuse effect tags with the
 * heuristic floor, parameterize + redact, and render a standard Agent Skill
 * directory. If the LLM exhausts its schema-repair budget on any pass, fall
 * back to the zero-LLM template so demonstrated work is never lost (§8).
 */
export async function distillSemantic(
  recording: Recording,
  backend: LlmBackend,
  opts: DistillOptions,
): Promise<SkillDirectory> {
  assertSingleSegment(recording);
  try {
    const [intent, params, llmEffects, narrative] = await Promise.all([
      inferIntent(recording, backend),
      inferParams(recording, backend),
      inferEffects(recording, backend),
      narrate(recording, backend),
    ]);

    const effects = recording.steps.map((step, i) => combineEffect(step, llmEffects[i]!));
    const slug = toSlug(opts.name ?? intent.title ?? recording.title);

    const rendered: RenderedStep[] = recording.steps.map((step, i) => {
      const r: RenderedStep = {
        index: i,
        type: step.type,
        effect: effects[i]!,
        selectors: step.selectors ?? [],
        narrative: narrative[i] ?? { description: `${step.type} step`, agentStep: false },
      };
      if (typeof step.value === "string") r.value = rewriteValue(step.value, params);
      if (typeof step.url === "string") r.url = redactUrl(step.url);
      return r;
    });

    const files: Record<string, string> = {
      "SKILL.md": renderSkillMd(slug, intent.title, intent.description, params, rendered),
      "scripts/replay.ts": renderReplayScript(slug, rendered),
      "references/walkthrough.md": renderWalkthrough(intent.title, rendered),
      "references/CHANGELOG.md": renderChangelog(slug, recording["x-skillwright"].segment.recordedAt),
      "assets/recording.json": JSON.stringify(redactedRecording(recording, params, effects), null, 2),
    };

    // Second-pass redaction net: nothing secret-shaped survives in any file.
    for (const key of Object.keys(files)) files[key] = scrubText(files[key]!);
    return { slug, files };
  } catch (err) {
    if (err instanceof SchemaExhaustedError) return distill(recording, opts);
    throw err;
  }
}
