import {
  assertSingleSegment,
  classifyStepEffect,
  type EffectTag,
  type Recording,
  type Step,
} from "@skillwright/shared";
import { toSlug } from "./slug";
import { stepLabel } from "./step-label";

export interface DistillOptions {
  name?: string;
}

export interface SkillDirectory {
  slug: string;
  files: Record<string, string>;
}

interface TaggedStep {
  index: number;
  step: Step;
  label: string | undefined;
  effect: EffectTag;
}

function tagSteps(recording: Recording): TaggedStep[] {
  return recording.steps.map((step, index) => {
    const label = stepLabel(step);
    const effect = step.effect ?? classifyStepEffect({ action: step.type, label });
    return { index, step, label, effect };
  });
}

function describeStep(t: TaggedStep): string {
  const target = t.label ? `"${t.label}"` : "the target element";
  switch (t.step.type) {
    case "click":
      return `Click ${target}`;
    case "change":
    case "input":
      return `Enter the value into ${target}`;
    case "navigate":
      return `Navigate to the page`;
    default:
      return `${t.step.type} on ${target}`;
  }
}

function renderSkillMd(slug: string, title: string, tagged: TaggedStep[]): string {
  const hasDestructive = tagged.some((t) => t.effect === "destructive");
  const description =
    `${title}. Use when asked to perform this task in the browser` +
    (hasDestructive ? " (contains steps that change or delete data)." : ".");
  const frontmatter = [
    "---",
    `name: ${slug}`,
    `description: ${description}`,
    "compatibility: Requires Node 20+, a Chrome CDP endpoint (skillwright relay), and an authenticated session in that browser.",
    "metadata:",
    "  author: skillwright",
    '  version: "1.0"',
    "---",
  ].join("\n");
  const body = [
    ``,
    `# ${title}`,
    ``,
    `Replay with \`skillwright run ${slug}\`. Full step detail, selector stacks, and`,
    `screenshots are in \`references/walkthrough.md\`.`,
    ``,
    `## Steps`,
    ...tagged.map((t) => `${t.index + 1}. [${t.effect}] ${describeStep(t)}`),
    ``,
  ].join("\n");
  return frontmatter + "\n" + body;
}

function renderWalkthrough(title: string, tagged: TaggedStep[]): string {
  const lines = [`# ${title} — walkthrough`, ``];
  for (const t of tagged) {
    lines.push(`## Step ${t.index + 1}: ${describeStep(t)}`);
    lines.push(`- effect: ${t.effect}`);
    const stacks = t.step.selectors ?? [];
    if (stacks.length > 0) {
      lines.push(`- selectors (most stable first):`);
      for (const stack of stacks) lines.push(`  - ${stack.join(" → ")}`);
    }
    lines.push(``);
  }
  return lines.join("\n");
}

function renderReplayScript(slug: string, tagged: TaggedStep[]): string {
  // M1 template: a deterministic Playwright-over-CDP driver skeleton. The
  // effect tags travel into the script so the run-time safety gate can read
  // them without re-classifying.
  const steps = tagged.map((t) => ({
    type: t.step.type,
    effect: t.effect,
    selectors: t.step.selectors ?? [],
  }));
  return [
    `// Auto-generated by skillwright distill for "${slug}". Do not hand-edit;`,
    `// re-run distill or let a heal write back through the CLI.`,
    `import { chromium } from "playwright";`,
    ``,
    `export const steps = ${JSON.stringify(steps, null, 2)} as const;`,
    ``,
    `export async function run(cdpUrl = process.env.CHROME_CDP_URL) {`,
    `  if (!cdpUrl) throw new Error("CHROME_CDP_URL is not set — start 'skillwright relay'.");`,
    `  const browser = await chromium.connectOverCDP(cdpUrl);`,
    `  // ... per-step selector-stack execution lands with the replay driver.`,
    `  return browser;`,
    `}`,
    ``,
  ].join("\n");
}

function renderChangelog(slug: string, recordedAt: string): string {
  return [
    `# Changelog — ${slug}`,
    ``,
    `## 1.0 — distilled`,
    `- Created from recording captured ${recordedAt} (skillwright distill, template mode).`,
    ``,
  ].join("\n");
}

/**
 * Zero-LLM (M1) distiller: turn a single-segment recording into a standard
 * Agent Skill directory. Refuses multi-segment input loudly (never drops data).
 */
export function distill(recording: Recording, opts: DistillOptions): SkillDirectory {
  assertSingleSegment(recording);
  const slug = toSlug(opts.name ?? recording.title);
  const tagged = tagSteps(recording);
  // Effect tags are written back into the recording's steps (§6.1.4) so
  // recording.json is the single source of truth for effect-by-original-index.
  const taggedRecording: Recording = {
    ...recording,
    steps: recording.steps.map((step, i) => ({ ...step, effect: tagged[i]!.effect })),
  };
  return {
    slug,
    files: {
      "SKILL.md": renderSkillMd(slug, recording.title, tagged),
      "scripts/replay.ts": renderReplayScript(slug, tagged),
      "references/walkthrough.md": renderWalkthrough(recording.title, tagged),
      "references/CHANGELOG.md": renderChangelog(slug, recording["x-skillwright"].segment.recordedAt),
      "assets/recording.json": JSON.stringify(taggedRecording, null, 2),
    },
  };
}
